language: node_js
node_js:
  - "5.2"
  - "4.1"
env:
  - NODE_ENV=travis
services:
  - mongodb
before_install:
- npm install -g bower grunt-cli
- bower install
install:
- npm install
- bower install
script:
- grunt
